name: dice_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"
  
flutter_launcher_icons:
  image_path: "images/app-logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
